[package]
name = "cosmic-files-applet"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
zbus = "5"

[dependencies.cosmic-files]
path = ".."
default-features = false
features = ["desktop", "gvfs", "wayland", "wgpu", "desktop-applet"]
