[package]
name = "cosmic-files-applet"
version = "1.0.8"
edition = "2024"

[dependencies]
log = "0.4"
zbus = "4" # Blocking connection in zbus 5 hangs

[dependencies.cosmic-files]
path = ".."
default-features = false
features = ["desktop", "gvfs", "wayland", "desktop-applet"]
